services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=wg-easy.vpn.hobbscene.com # The public hostname of your VPN server.

      # Optional:
      - PASSWORD_HASH=${PASSWORD_HASH} # When set, requires a password when logging in to the Web UI.
      - WG_PORT=51820 # The public UDP port of your VPN server. WireGuard will always listen on 51820 inside the Docker container.
      - WG_DEFAULT_ADDRESS=10.8.0.x # Clients IP address range.
      - WG_DEFAULT_DNS=192.168.1.131 # DNS server clients will use.
      # - WG_DEFAULT_DNS=1.1.1.1 # DNS server clients will use.
      - WG_MTU=1420 # The MTU the clients will use. Server uses default WG MTU.
      - WG_ALLOWED_IPS=192.168.1.0/24, 10.8.0.0/24 # Allowed IPs clients will use.
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_POST_UP=iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - WG_POST_UP=ip route add 192.168.1.0/24 dev eth0 scope link || true; iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
      # - WG_POST_DOWN=iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
      - WG_POST_UP=iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o macvlan-shim -j MASQUERADE; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
      - WG_POST_DOWN=iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -o macvlan-shim -j MASQUERADE; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    volumes:
      - /home/tim/Public/git/docker/wg-easy:/etc/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    # ports:
    #   - "51820:51820/udp"
    #   - "51821:51821/tcp"
    # sysctls:
    #   - net.ipv4.ip_forward=1
    #   - net.ipv4.conf.all.src_valid_mark=1
    #   - net.ipv6.conf.all.disable_ipv6=0
    #   - net.ipv6.conf.all.forwarding=1
    #   - net.ipv6.conf.default.forwarding=1
    # networks:
    #   # proxy:
    #   macvlan:
    #     ipv4_address: 192.168.1.254
    network_mode: "host"
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # HTTP Redirect
      - traefik.http.routers.vpn-http.entrypoints=http
      - traefik.http.routers.vpn-http.rule=Host(`wg-easy.vpn.hobbscene.com`)
      - traefik.http.routers.vpn-http.middlewares=vpn-https-redirect
      - traefik.http.middlewares.vpn-https-redirect.redirectscheme.scheme=https
      # HTTPS Secure
      - traefik.http.routers.vpn-secure.entrypoints=https
      - traefik.http.routers.vpn-secure.rule=Host(`wg-easy.vpn.hobbscene.com`)
      - traefik.http.routers.vpn-secure.tls=true
      - traefik.http.routers.vpn-secure.service=vpn-service # Custom service name
      # - traefik.http.services.vpn-service.loadbalancer.server.port=51821
      - traefik.http.services.vpn-service.loadbalancer.server.url=http://192.168.1.101:51821
      - homepage.group=Security
      - homepage.name=WireGuard
      - homepage.description=Easy-to-use WireGuard VPN server
      - homepage.icon=wireguard
      - homepage.href=https://wg-easy.vpn.hobbscene.com
      - homepage.widget.type=wgeasy
      - homepage.widget.url=http://192.168.1.101:51821
      - homepage.widget.password=${UI_PASS}
      - homepage.widget.fields=["connected", "enabled", "disabled", "total"]

networks:
  proxy:
    external: true
  macvlan:
    external: true