services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=vpn.media.hobbscene.com # The public hostname of your VPN server.

      # Optional:
      - PASSWORD_HASH=${UI_PASS} # When set, requires a password when logging in to the Web UI.
      - WG_PORT=51820 # The public UDP port of your VPN server. WireGuard will always listen on 51820 inside the Docker container.
      - WG_DEFAULT_ADDRESS=10.8.0.x # Clients IP address range.
      - WG_DEFAULT_DNS=8.8.8.8 # DNS server clients will use.
      - WG_MTU=1420 # The MTU the clients will use. Server uses default WG MTU.
      - WG_ALLOWED_IPS=192.168.1.0/24, 10.0.1.0/24 # Allowed IPs clients will use.
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    volumes:
      - /home/tim/Public/git/docker/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.vpn.entrypoints=http"
      - "traefik.http.routers.vpn.rule=Host(`vpn.media.hobbscene.com`)"
      - "traefik.http.middlewares.vpn-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.vpn.middlewares=vpn-https-redirect"
      - "traefik.http.routers.vpn-secure.entrypoints=https"
      - "traefik.http.routers.vpn-secure.rule=Host(`vpn.media.hobbscene.com`)"
      - "traefik.http.routers.vpn-secure.tls=true"
      - "traefik.http.routers.vpn-secure.service=vpn"
      - "traefik.http.services.vpn.loadbalancer.server.port=51821"

networks:
  proxy:
    external: true