secrets:
  cf-token:
    file: ./cf-token
services:
  traefik:
    image: traefik:latest # or traefik:v3.3 to pin a version
    container_name: traefik
    restart: unless-stopped
    stdin_open: true
    tty: true
    security_opt:
      - no-new-privileges:true # helps to increase security
    secrets:
      - cf-token # the secret at the top of this file
    env_file:
      - .env # store other secrets e.g., dashboard password
    networks:
      proxy:
    command:
      - --entryPoints.mc-bedrock.address=:19132/udp
    ports:
      - 80:80
      - 81:81
      - 443:443
      - 444:444
      - 8800:8080
      - 19132:19132/udp # Minecraft Bedrock Edition default port, adjust if needed
      # - 10000:10000 # optional
      # - 33073:33073 # optional
    environment:
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf-token # see https://doc.traefik.io/traefik/https/acme/#providers
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/tim/Public/git/docker/traefik/traefik.yaml:/traefik.yaml:ro
      - /home/tim/Public/git/docker/traefik/acme.json:/acme.json
      - /home/tim/Public/git/docker/traefik/rules:/rules
      - /home/tim/Public/git/docker/traefik/logs:/var/log/traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.rule=Host(`traefik.media.hobbscene.com`)
      - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.traefik.middlewares=traefik-https-redirect
      - traefik.http.routers.traefik-secure.entrypoints=https
      - traefik.http.routers.traefik-secure.rule=Host(`traefik.media.hobbscene.com`)
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.tls.certresolver=cloudflare
      - traefik.http.routers.traefik-secure.tls.domains[0].main=media.hobbscene.com
      - traefik.http.routers.traefik-secure.tls.domains[0].sans=*.media.hobbscene.com
      - traefik.http.routers.traefik-secure.tls.domains[1].main=vpn.hobbscene.com
      - traefik.http.routers.traefik-secure.tls.domains[1].sans=*.vpn.hobbscene.com
      - traefik.http.routers.traefik-secure.service=api@internal

      - traefik.http.routers.api.rule=Host(`traefik.media.hobbscene.com`) && PathPrefix(`/api`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.tls=true

      - homepage.group=Networking
      - homepage.name=Traefik (Media)
      - homepage.description=Modern reverse proxy and load balancer
      - homepage.href=https://traefik.media.hobbscene.com
      - homepage.icon=traefik
      - homepage.widget.type=traefik
      - homepage.widget.url=https://traefik.media.hobbscene.com
      - homepage.widget.username=${TRAEFIK_USERNAME}
      - homepage.widget.password=${TRAEFIK_PASSWORD}
      - homepage.widget.fields=["routers", "services", "middleware"]

networks:
  proxy:
    external: true # or comment this line to auto create the network