services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000 # optional, your user id
      PGID: 1000 # optional, your group id
      HOMEPAGE_ALLOWED_HOSTS: homepage.media.hobbscene.com
    volumes:
      - /home/tim/Public/git/docker/homepage:/app/config
      - /home/tim/Public/git/docker/homepage/icons:/opt/homepage/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3000:3000
    networks:
      proxy:
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.homepage.entrypoints=http
      - traefik.http.routers.homepage.rule=Host(`homepage.media.hobbscene.com`)
      - traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.homepage.middlewares=homepage-https-redirect
      - traefik.http.routers.homepage-secure.entrypoints=https
      - traefik.http.routers.homepage-secure.rule=Host(`homepage.media.hobbscene.com`)
      - traefik.http.routers.homepage-secure.tls=true
      # - traefik.http.routers.homepage-secure.tls.certresolver=cloudflare
      - traefik.http.routers.homepage-secure.service=homepage
      - traefik.http.routers.homepage-secure.middlewares=authentik-media@docker
      - traefik.http.services.homepage.loadbalancer.server.port=3000

networks:
  proxy:
    external: true