services:
  tvheadend:
    image: lscr.io/linuxserver/tvheadend:latest
    container_name: tvheadend
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=America/Los_Angeles
      - RUN_OPTS= #optional
    volumes:
      - /home/tim/xmltv/grabbers:/usr/bin
      - /home/tim/Public/git/docker/tvheadend/config:/config
      - seagate_dvr:/recordings
    network_mode: host
    # devices:
    #   - /dev/dri:/dev/dri #optional
    #   - /dev/dvb:/dev/dvb #optional
    restart: unless-stopped

  tvheadend-proxy:
    image: nginx:alpine
    container_name: tvheadend-proxy
    networks:
      proxy:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/tim/Public/git/docker/tvheadend/proxy.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.tvhe.entrypoints=http"
      - "traefik.http.routers.tvhe.rule=Host(`tvhe.media.hobbscene.com`)"
      - "traefik.http.middlewares.tvhe-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.tvhe.middlewares=tvhe-https-redirect"
      - "traefik.http.routers.tvhe-secure.entrypoints=https"
      - "traefik.http.routers.tvhe-secure.rule=Host(`tvhe.media.hobbscene.com`)"
      - "traefik.http.routers.tvhe-secure.tls=true"
      # - "traefik.http.routers.tvhe-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.tvhe-secure.service=tvhe"
      # - "traefik.http.routers.tvhe-secure.middlewares=auth"
      - "traefik.http.services.tvhe.loadbalancer.server.port=80"
      - homepage.group=Media
      - homepage.name=tvhe
      - homepage.description=TV streaming server and DVR
      - homepage.href=https://tvhe.media.hobbscene.com
      - homepage.icon=tvheadend

volumes:
  seagate_dvr:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: '/media/tim/seagate500gb/dvr'

networks:
  proxy:
    external: true